### ISSUE TITLE
Setting verbosity level INFO also invokes REPORT

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.utils#135]
I am using the LogReporter and the logger from RU in EnTK. Setting the verbosity level to INFO also invokes the REPORT level. Is there a way to disable one when the other is in use? (I understand DEBUG level is intended to invoke INFO messages as well)

**Comment by andre-merzky** [comment]
The reason is [here](https://github.com/radical-cybertools/radical.utils/blob/devel/src/radical/utils/logger.py#L278) : we set the `REPORT` level is higher than the `INFO` level.  I also find this annoying, and the agree that the settings for logging and reporting should be separated, so I don't mind implementing / fixing this.  

Whats the priority on this?

**Comment by vivek-bala** [comment]
Its not critical, I have already released EnTK with the reporter. It'll be good to keep the issue in the agenda for the next major release.

**Comment by andre-merzky** [comment]
This should be fixed by now.
