### ISSUE TITLE
get_hostname does not work with python3 on Mac

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.utils#205]
I see the following error:
```
(campaign) iparaskmac:campaign_manager iparask$ python
Python 3.8.1 | packaged by conda-forge | (default, Jan  5 2020, 20:40:51)
[Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from radical.utils.misc import get_hostname as ru_hostname
>>> ru_hostname()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/iparask/anaconda3/envs/campaign/lib/python3.8/site-packages/radical/utils/misc.py", line 435, in get_hostname
    _hostname = socket.gethostbyaddr(socket.gethostname())[0]
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
>>>
```

This error gets triggered when I'm trying to create a `Profiler` object. In addition,
```
>>> socket.gethostname()
'iparaskmac'
>>> socket.gethostbyaddr(socket.gethostname())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
>>>
```

**Comment by andre-merzky** [comment]
Puh...  I am hesitant to work around this, since (a) this kind of is the canonical way to obtain the hostname in POSIX, (b) most other routes are more error prone (like shell callout to `hostname -f` or DNS lookups), and (c) MacOS is not really supported anyway.

In good old Python fashion this is a [know problem](https://bugs.python.org/issue35164).  I would like to suggest you try one of the workarounds discussed there?  We can revisit a proper in fix in RU if users stumble over it, IMHO.  What do you think?

**Comment by iparask** [comment]
Yes, I agree. I'll let you know how it goes.

**Comment by andre-merzky** [comment]
I am closing this as out of scope - but if you find a solution, it might be worth adding that to the docs (FAQ or so?).  Thanks!
