### ISSUE TITLE
Name for cnt-file (inside method generate_id) is defined incorrectly

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.utils#222]
Example: `~/.radical/utils/rp.session<…>/ru_matitov_pilot.%(item_counter)04d.cnt`
(code where name is defined is [here](https://github.com/radical-cybertools/radical.utils/blob/devel/src/radical/utils/ids.py#L261))

**Comment by mtitov** [comment]
BTW is the purpose of `~/.radical` dir to keep configs? should such files (as above) be kept at `sandbox` dir?

**Comment by andre-merzky** [comment]
I seem to be missing the point of the ticket (and of the PR #223), apologies @mtitov !  Can we restart the discussion, please?  So, why do you think that this is incorrectly defined - what exactly is broken?  Do you have a script to reproduce the problem?

> BTW is the purpose of ~/.radical dir to keep configs? should such files (as above) be kept at sandbox dir?

The `~/.radical` dir has two purposes: to have a place for the user to drop config files which overwrite or extend the configs provided by the RCT installation tree, and to keep state between runs (like counters and job information etc).  Neither of those would work feasible in a sandbox, as sandboxes are expected to be temporary and might disappear at any time.

**Comment by mtitov** [comment]
sure! agree to keep the discussion here

> So, why do you think that this is incorrectly defined - what exactly is broken?

just running the example `00_getting_started.py`, it creates files (see below) in the dir `/Users/matitov/.radical/utils/rp.session.MT-MBP-X2.local.matitov.018322.0000/`:
```
ru_matitov_pilot.%(item_counter)04d.cnt
ru_matitov_pmgr.%(item_counter)04d.cnt
ru_matitov_umgr.%(item_counter)04d.cnt
ru_matitov_unit.%(item_counter)06d.cnt
```
the code that is responsible for it is [here](https://github.com/radical-cybertools/radical.utils/blob/devel/src/radical/utils/ids.py#L261)

adding here my previous reply:
> I was a little confused with possible original purpose of it: either 1) always change the name with the current `item_counter` (read the current `item_counter`, delete corresponding file, and then create a new file with new `item_counter` in name and as a text inside); or 2) create a set of files while new value for `item_counter` appears (I understand that this option is less probable, but there is no deletions for the 1st option, and without knowing the value it wouldn’t be possible to read the file at the beginning).
> For now cannot come up with something more elegant. 

Also (from the previous reply) there is a proposal for small changes:
> to have a separate parameter new_template=None if mode==ID_CUSTOM, so not to mix with prefix parameter?

or to keep the changes from the related commit 3732f58

---

> `~/.radical` dir
> to keep state between runs (like counters and job information etc). Neither of those would work feasible in a sandbox, as sandboxes are expected to be temporary and might disappear at any time.

but counters suppose to be temporary as well? my worries are that there are several places which are filled up with operational data (I would expect to have only one such place). Configs are static and are used multiple times, counters are changed during the runtime and after processings are done should be cleaned up (?)

**Comment by andre-merzky** [comment]
> just running the example 00_getting_started.py, it creates files (see below) in the dir /Users/matitov/.radical/utils/rp.session.MT-MBP-X2.local.matitov.018322.0000/: [...]

Well, yes, that's correct, and that's the intent - I am still not sure why you think that this is broken?

The purpose of the counter files is as follows: we create UIDs in many different place, and specifically in different processes.  Some of those UIDs need to be globally unique (i.e., they should never collide), some need only to be unique within a pilot session, some are unique within some other scope.

We could trivially use UUIDs for that - with two drawbacks: they are not user friendly (very long, not memorable, UIDs for a pilot look the same as for a task, etc); and they cannot easily be sorted (well, not sensibly), making human navigation more difficult (like, selecting a sandbox of a specific task).  So, RU provides it's own UID generator.  For globally unique IDs, we encode host, day, user ID, and a user specific counter.  For pilot IDs, we only encode a prefix (`pilot.`), and use a session specific counter (`pilot.0000, pilot.0001, ...`).

Since UIDs are generated in different processes, and at different times, we need to keep track of UIDs which have been used: we would not want to have a `heartbeat.pubsub.0000` in both the agent scheduler and the agent executor, since (a) the heartbeat messages would get confused (they are signed by UID), config file names might collide, and logfiles are more difficult to parse.  So RU creates those files in `$RADICAL_BASE/utils/*.cnt` (`$RADICAL_BASE` defaults to `$HOME`), so that different processes don't use the same number of entities with the same name.  That are those files you see.

This might not be beautiful - but it works rather well, and is surprisingly efficient ( a million simple UIDs take about 5 seconds to generate, a million session IDs need about 15 seconds).  An alternative would be to use a database like msql - but so far there is no need, really.

So,   what is the use case which you consider broken at the moment?  Or what am I missing?

**Comment by mtitov** [comment]
yeah, sorry, my concern was that that files (*.cnt) have a template-like format in their names: currently it is `ru_matitov_pilot.%(item_counter)04d.cnt`, but I would expect `ru_matitov_pilot.cnt` ()

so I don't have any issues with unique names in general :) (that absolutely makes sense to split the processes and everything related)

speaking about sys-dirs, for that my session `rp.session.MT-MBP-X2.local.matitov.018322.0000` I have the following related directories:
```
/Users/matitov/Projects/radical.pilot/examples/rp.session.MT-MBP-X2.local.matitov.018322.0000
/Users/matitov/radical.pilot.sandbox/rp.session.MT-MBP-X2.local.matitov.018322.0000
/Users/matitov/.radical/utils/rp.session.MT-MBP-X2.local.matitov.018322.0000
```
and just was wondering that session related things would be kept together (e.g. in sandbox). Sorry that brought a lot of confusion

**Comment by andre-merzky** [comment]
Ah, I see.  That's on purpose, really.  I know it's ugly, but the template it really the only distinguishing element between the different UID name spaces.  Expanding the template might work in most cases (as collisions are unlikely), but if that happens, it would be very difficult to debug...

As for the three dirs with the session name:

The second sandbox is for the application you run, and is located in the PWD of the application.  So far so good.

The first one is the pilot sandbox - which usually is on the *remote resource*, and thus cannot be on the same file system.  You happen to submit the pilot to localhost here, which then gives you two directories on your local machine - but imagine you are running the application on your laptop, and the pilot run on Stampede in Texas...

The third one is the UID namespace we discussed above: that is truly temporary data.  It could also live in `/tmp/radical.$UID/...`, and in fact did live there for a while - but it happens that `/tmp` is usually not a shared file system on compute nodes, so the role as resource-wide store for those data items would be compromised.  I don't like  that this directory pollutes over time, and we probably should implement some opportunistic garbage collection which kicks in now and then - but otherwise this is functionally different than the session dir.    

I created #224 to track this though, lets ponder over this a bit.  Maybe we can keep session related tmp data in `$RADICAL_SESSION_BASE` if that is set (and fall back to the current behavior if not)? 
 Thanks for your input!
